# Generated by Django 2.2.10 on 2020-08-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20200805_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
