# Generated by Django 2.2.10 on 2020-08-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_customerinfo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
