# Generated by Django 2.2.10 on 2020-08-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_product_sale_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerInfo',
            new_name='ReciverInfo',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customerinfo',
            new_name='receiver',
        ),
    ]
