# Generated by Django 2.2.10 on 2020-08-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20200807_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciverinfo',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
    ]
